// <auto-generated />
using System;
using EinzelhandelCoreMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EinzelhandelCoreMVC.Migrations
{
    [DbContext(typeof(MVCEinzelhandelContext))]
    [Migration("20190926224847_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EinzelhandelCoreMVC.Models.Produkt", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ProduktartID");

                    b.Property<int>("Titel")
                        .HasMaxLength(50);

                    b.Property<int>("Zahl");

                    b.HasKey("ID");

                    b.HasIndex("ProduktartID");

                    b.ToTable("Produkt");
                });

            modelBuilder.Entity("EinzelhandelCoreMVC.Models.Produktart", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("Produktart");
                });

            modelBuilder.Entity("EinzelhandelCoreMVC.Models.Produkt", b =>
                {
                    b.HasOne("EinzelhandelCoreMVC.Models.Produktart", "Produktart")
                        .WithMany("Produkts")
                        .HasForeignKey("ProduktartID");
                });
#pragma warning restore 612, 618
        }
    }
}
